// Copyright Epic Games, Inc. All Rights Reserved.

using System.IO;
using UnrealBuildTool;
using System.Collections.Generic;
using System.Text;
using System;

public class RococoUtil : ModuleRules
{
    private string rococoIncludeDirectory;
	private string rococoHomeDirectory;
    private string rococoSourceDirectory;
	private string thisSourceDirectory;

    private void PrepRococoDirectories()
	{
        if (rococoIncludeDirectory == null)
        {
            string dir = PluginDirectory;
            string fullPath = dir;
            string lastFullPath;

            do
            {
                lastFullPath = fullPath;

                fullPath = Path.GetFullPath(Path.Combine(fullPath, ".."));

                string candidateIncludeDirectory = Path.Combine(fullPath, "source/rococo/include/");
                if (Directory.Exists(candidateIncludeDirectory))
                {
					rococoHomeDirectory = fullPath;
                    rococoIncludeDirectory = candidateIncludeDirectory;
					rococoSourceDirectory = Path.Combine(fullPath, "source");
					thisSourceDirectory = Path.Combine(PluginDirectory, "Source/RococoUtil/Private");
					if (!Directory.Exists(thisSourceDirectory))
					{
						throw new System.Exception("Expecting directory to exist: " + thisSourceDirectory);
                    }
                    return;
                }

            } while (lastFullPath != fullPath);

            throw new System.Exception("Could not find rococo directory by enumerating ancestors of " + dir);
        }
    }

    private void CreateBundleDirect(string bundleName, string inlName, string sourceDirectory, List<string> sourceNames)
    {
		StringBuilder sb = new StringBuilder();

		sb.AppendLine("// Bundle generated by Rococo.Util.Build.cs");
		sb.AppendLine("// Created: " + DateTime.UtcNow.ToString("d MMM yyyy HH:mm:ss") + " UTC");
		sb.AppendLine();

		if (inlName != null)
		{
			sb.AppendLine("#include \"" + inlName + "\"");
        }

        foreach (var sourceName in sourceNames)
		{
			string fullPath = Path.Combine(rococoSourceDirectory, sourceDirectory, sourceName);
			if (!File.Exists(fullPath))
			{
				throw new System.Exception("Could not find bundle file" + fullPath);
			}

			fullPath = fullPath.Replace("\\", "/");

			sb.AppendFormat("#include <{0}>", fullPath);
			sb.AppendLine();
		}

		string fullBundlePath = Path.Combine(thisSourceDirectory, bundleName);
		if (!fullBundlePath.EndsWith(".rococo-bundle.cpp"))
		{
			throw new System.Exception("Expecting bundle file to end with .rococo-bundle.cpp");
		}

		if (File.Exists(fullBundlePath))
		{
			string existingText = File.ReadAllText(fullBundlePath);
			if (sb.ToString() != existingText)
			{
				File.WriteAllText(fullBundlePath, sb.ToString());
			}
		}
    }


	private void CreateBundles()
	{
		List<string> utilBundleFiles = new List<string>()
		{
			"rococo.strings.cpp",
			"rococo.base.cpp",
			"rococo.heap.string.cpp"
		};

        CreateBundleDirect("rococo.util.rococo-bundle.cpp", "rococo.util.header.inl", "rococo/rococo.util", utilBundleFiles);
	}

    public string RococoIncludeDirectory
	{
		get { return rococoIncludeDirectory; }
	}

    public string RococoHomeDirectory
    {
        get { return rococoHomeDirectory; }
    }

    public RococoUtil(ReadOnlyTargetRules Target) : base(Target)
	{
        PrepRococoDirectories();
		CreateBundles();

		PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;

		PublicIncludePaths.AddRange(
			new string[] {
                RococoIncludeDirectory
            }
			);
				
		
		PrivateIncludePaths.AddRange(
			new string[] {
				// ... add other private include paths required here ...
			}
			);
			
		
		PublicDependencyModuleNames.AddRange(
			new string[]
			{
				"Core",
				// ... add other public dependencies that you statically link with here ...
			}
			);
			
		
		PrivateDependencyModuleNames.AddRange(
			new string[]
			{
				"CoreUObject",
				"Engine",
				"Slate",
				"SlateCore",
				// ... add private dependencies that you statically link with here ...	
			}
			);
		
		
		DynamicallyLoadedModuleNames.AddRange(
			new string[]
			{
				// ... add any modules that your module loads dynamically here ...
			}
			);
	}
}
