// Generated by Build.Rococo.GUI.cs. Copied from D:\work\rococo\UE5\RococoTestFPS\Plugins\RococoGui\Source\RococoGui\Private\GameOptionBuilder.cpp on Oct 2025 UTC

#include <GameOptionBuilder.h>

void IRococoGameOptionBuilder::RaiseError(const FString& methodMsg, const FString& propertyMsg, const FString& errMsg)
{
	OnError(methodMsg, propertyMsg, errMsg);
}

void IRococoGameOptionBuilder::Accept()
{
	OnAccept();
}

void IRococoGameOptionBuilder::Revert()
{
	OnRevert();
}

void IRococoGameOptionBuilder::InvokeInitOptions()
{
	InitOptions();
}

FString IRococoGameOptionBuilder::RaiseGetOptionId()
{
	return TEXT("IRococoGameOptionBuilder: RaiseGetOptionId - default");
}

