// Generated by Build.Rococo.GUI.cs. Copied from D:\work\rococo\Source\3rd-Party\libjpg\jpeg-6b\jversion.h on Oct 2025 UTC

/*
 * jversion.h
 *
 * Copyright (C) 1991-1998, Thomas G. Lane.
 * This file is part of the Independent JPEG Group's software.
 * For conditions of distribution and use, see the accompanying README file.
 *
 * This file contains software version identification.
 */


#define JVERSION	"6b  27-Mar-1998"

#define JCOPYRIGHT	"Copyright (C) 1998, Thomas G. Lane"

