// Generated by Build.Rococo.GUI.cs. Copied from D:\work\rococo\UE5\RococoTestFPS\Plugins\RococoGui\Source\RococoGui\Private\RococoGui_BPEvents.cpp on Oct 2025 UTC

#include <RococoGui_BPevents.h>

void IRococoReflectionEventHandler::RaiseBadMethod(const FString& errMsg, const FString& methodMsg, const FString& propMsg)
{
	OnBadMethod(errMsg, methodMsg, propMsg);
}

