// Generated by Build.Rococo.GUI.cs. Copied from D:\work\rococo\UE5\RococoTestFPS\Plugins\RococoGui\Source\RococoGui\Private\RococoFontSet.cpp on Oct 2025 UTC

#include "RococoFontSet.h"
#include "rococo.GR.UE5.h"

FName URococoFontSet::MapTypeface(const FName& typefaceName)
{
	const FName* pResultantName = _RequestedTypeFaceToResultantTypeFace.Find(typefaceName);
	return pResultantName ? *pResultantName : NAME_None;
}
