// Bundle generated by Build.Rococo.GUI.cs
// Created: Oct 2025 UTC

// Copyright (c)2025 Mark Anthony Taylor (mark.anthony.taylor@gmail.com). All rights reserved.
// This software is open source, but not free. Check the rococo master branch for the latest Copyright rules that applies to this software

#include "rococo.UE5.cpp.h"

#ifdef _WIN32
# pragma warning(disable: 4458) // this is my coding style and I don't see many errors arising out of the choice of style
# pragma warning(disable: 4265) // virtualized destructors are irrelevant for these classes using the Free() pattern
#else
# pragma clang diagnostic push
# pragma clang diagnostic ignored "-Wshadow"
# pragma clang diagnostic ignored "-Wdelete-non-abstract-non-virtual-dtor"
# pragma clang diagnostic ignored "-Woverloaded-virtual"
# pragma clang diagnostic ignored "-Wmissing-braces"
#endif
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.button.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.carousel.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.collapser.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.control-prompt.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.division.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.editbox.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.game-options.bool.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.game-options.choice.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.game-options.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.game-options.scalar.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.game-options.string.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.gradient-fill.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.hintbox.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.icon.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.label-text.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.layout.fullscreen.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.mainframe.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.menubar.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.panel.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.portrait.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.property-editor-tree.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.radio-buttons.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.scheme.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.scrollable-menu.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.slider.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.splitter.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.system.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.table.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.toolbar.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.vertical-list.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.vertical.scroller.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.vertical.scroller.with.buttons.cpp>
#include <D:/work/rococo/source/rococo/rococo.gui.retained/rococo.gr.viewport.cpp>
#ifdef _WIN32
# pragma warning(default: 4458)
# pragma warning(default: 4265)
#else
# pragma clang diagnostic pop
#endif
