// Bundle generated by Build.Rococo.GUI.cs
// Created: Oct 2025 UTC

#include "rococo.UE5.cpp.h"
// Copyright (c)2025 Mark Anthony Taylor (mark.anthony.taylor@gmail.com). All rights reserved.
// This software is open source, but not free. Check the rococo master branch for the latest Copyright rules that applies to this software

#include "rococo.UE5.cpp.h"

#ifdef _WIN32
# pragma warning(disable: 4458) // this is my coding style and I don't see many errors arising out of the choice of style
# pragma warning(disable: 4265) // virtualized destructors are irrelevant for these classes using the Free() pattern
#else
# pragma clang diagnostic push
# pragma clang diagnostic ignored "-Wshadow"
# pragma clang diagnostic ignored "-Wdelete-non-abstract-non-virtual-dtor"
# pragma clang diagnostic ignored "-Woverloaded-virtual"
# pragma clang diagnostic ignored "-Wmissing-braces"
#endif
#include <D:/work/rococo/source/rococo/sexy/SP/sexy.s-parser/sexy.s-parser.cpp>
#include <D:/work/rococo/source/rococo/sexy/SP/sexy.s-parser/sexy.s-builder.cpp>
#include <D:/work/rococo/source/rococo/sexy/SP/sexy.s-parser/sexy.s-parser.s-block.cpp>
#ifdef _WIN32
# pragma warning(default: 4458)
# pragma warning(default: 4265)
#else
# pragma clang diagnostic pop
#endif
