// Generated by Build.Rococo.GUI.cs. Copied from D:\work\rococo\UE5\RococoTestFPS\Plugins\RococoOS\source\RococoOS\private\rococo.OS.UE5.cpp at Oct 2025 UTC

#include "D:\work\rococo\UE5\RococoTestFPS\Plugins\RococoOS\source\RococoOS\private\rococo.OS.UE5.cpp"