// Generated by Build.Rococo.GUI.cs. Copied from D:\work\rococo\UE5\RococoTestFPS\Plugins\RococoGui\source\RococoGui\private\UE5.GR-Custodian.cpp at Oct 2025 UTC

#include "D:\work\rococo\UE5\RococoTestFPS\Plugins\RococoGui\source\RococoGui\private\UE5.GR-Custodian.cpp"