// Generated by gen_domme_objects.sxy on Sat Nov 23 21:54:02 2024

#pragma once

#include <rococo.domme.h>

namespace Rococo::Animals
{
    struct ICat
    {
        virtual void MakeBiscuits(int32 nBiscuits, float dt) = 0;
        virtual void Mew() = 0;
    };

    struct ICatSupervisor: ICat
    {
        virtual void SV_Free() = 0;
        virtual void SV_Terminate() = 0;
    };

    ICatSupervisor* CreateCat(Rococo::Domme::ScriptingResources& scripting, cstr sourceFile);
}

DECLARE_DOMME_INTERFACE(Rococo::Animals::ICatSupervisor)

