// Generated by gen_domme_objects.sxy on Mon Nov 11 09:58:37 2024

#pragma once

#include <rococo.domme.h>

namespace Rococo::Animals
{
    struct IDog
    {
        virtual void Bark(float hz = 512) = 0;
        virtual bool /* success */ GoWalkies(const Vec3& targetPosition) = 0;
        virtual void SetName(fstring name = "\tRover\r\n\x01"_fstring) = 0;
    };

    struct IDogSupervisor: IDog
    {
        virtual void SV_Free() = 0;
        virtual void SV_Terminate() = 0;
    };

    IDogSupervisor* CreateDog(Rococo::Domme::ScriptingResources& scripting, cstr sourceFile);
}

DECLARE_DOMME_INTERFACE(Rococo::Animals::IDogSupervisor)

