#pragma once

// Generated by BennyHill on 11/3/2025 8:59:22 UTC

namespace Rococo { namespace Audio { 
	struct AudioSource3D
	{
		int32 priority;
		float volume;
		Vec3 position;
		Vec3 dopplerVelocity;
		float msDelay;
	};
}}
