#pragma once

// Generated by BennyHill on 1/8/2023 10:45:53 UTC

namespace Rococo { namespace Audio { 
	struct AudioSource3D
	{
		int32 priority;
		float volume;
		Vec3 position;
		Vec3 dopplerVelocity;
		float msDelay;
	};
}}
