#pragma once

// Generated by BennyHill on 12/10/2023 18:43:3 UTC

namespace Rococo { namespace Audio { 
	struct AudioSource3D
	{
		int32 priority;
		float volume;
		Vec3 position;
		Vec3 dopplerVelocity;
		float msDelay;
	};
}}
