// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
// Bundle generated by Build.Rococo.GUI.cs
// Created: Oct 2025 UTC
#pragma once

#include "D:\work\rococo\source\3rd-Party\libjpg\jpeg-6b\jdatastream.h"
