// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
// Bundle generated by Build.Rococo.GUI.cs on Nov 2025 UTC
#pragma once

#include "D:\work\rococo\source\3rd-Party\libjpg\jpeg-6b\jinclude.h"
