// Bundle generated by Rococo.TiffJPEG.Build.cs
// Created: 14 Jun 2025 19:40:05 UTC

#include "rococo.jpg.UE5.h"
#ifdef _WIN32
# pragma warning(disable: 4456)
# pragma warning(disable: 4459)
# pragma warning(disable: 4996)
#else
#endif
#include "D:/work/rococo/source/3rd-Party/libjpg/jpeg-6b/jutils.c"
#ifdef _WIN32
# pragma warning(default: 4456)
# pragma warning(default: 4459)
# pragma warning(default: 4996)
#else
#endif
