// Bundle generated by Rococo.TiffJPEG.Build.cs
// Created: 15 Jun 2025 10:20:19 UTC

#include "rococo.jpg.UE5.h"
#ifdef _WIN32
# pragma warning(disable: 4456)
# pragma warning(disable: 4459)
# pragma warning(disable: 4996)

// 4661 allows setjmp to compile. I have gone at lengths to make sure it does not cause issues with C++ where it is used in libJPG and I see no evidence of vulnerability
# pragma warning(disable: 4611)
#else
#endif
#include "D:/work/rococo/source/3rd-Party/libjpg/jpeg-6b/jdatafromem.c"
#ifdef _WIN32
# pragma warning(default: 4456)
# pragma warning(default: 4459)
# pragma warning(default: 4996)
# pragma warning(default: 4611)
#else
#endif
