// Bundle generated by Rococo.TiffJPEG.Build.cs
// Created: 15 Jun 2025 17:07:25 UTC

#include "rococo.jpg.UE5.h"
#pragma once
#include "rococo.jpg.prelude.h"
#include "rococo.jpeg.decl.h"

#include "D:/work/rococo/source/3rd-Party/libjpg/writeimage.cpp"
#ifdef _WIN32
# pragma warning(default: 4456)
# pragma warning(default: 4459)
# pragma warning(default: 4996)
# pragma warning(default: 4611)
#else
#endif
