// Bundle generated by Rococo.TiffJPEG.Build.cs
// Created: 15 Jun 2025 14:25:34 UTC

#include "rococo.jpg.UE5.h"
#pragma once
#include "rococo.jpg.prelude.h"

#ifndef _WIN32

#include <stdarg.h>
enum {_TRUNCATE = -1 };
int _vsnprintf_s(char* message, size_t capacity, size_t nBytesToWrite, cstr format, va_list args);
#endif
#include "D:/work/rococo/source/3rd-Party/libjpg/readimage.cpp"
#ifdef _WIN32
# pragma warning(default: 4456)
# pragma warning(default: 4459)
# pragma warning(default: 4996)
# pragma warning(default: 4611)
#else
#endif
