; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25547.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Mark Anthony Taylor\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
