#pragma once

#ifndef ROCOCO_UE5_EXPORT
# ifdef ROCOCO_BUILD_IS_MONOLITHIC
#  define ROCOCO_UE5_EXPORT
#  define ROCOCO_UE5_IMPORT
# else
#  define ROCOCO_UE5_EXPORT DLLEXPORT
#  define ROCOCO_UE5_IMPORT DLLIMPORT
# endif
#endif

#ifndef ROCOCO_API
# define ROCOCO_API ROCOCO_UE5_IMPORT
#endif
#define ROCOCO_WINDOWS_API		ROCOCO_UE5_IMPORT
#define ROCOCO_UTIL_API			ROCOCO_UE5_IMPORT
#define SEXYUTIL_API			ROCOCO_UE5_EXPORT
#define SCRIPTEXPORT_API		ROCOCO_UE5_EXPORT
#define ROCOCO_SEXML_API		ROCOCO_UE5_EXPORT
#define ROCOCO_GUI_RETAINED_API ROCOCO_UE5_EXPORT
#define ROCOCO_GREAT_SEX_API	ROCOCO_UE5_EXPORT

#define ROCOCO_USE_SAFE_V_FORMAT
