#include "unreal-sexy-gen.h"
#include <rococo.strings.h>
#include <rococo.io.h>
#include <rococo.os.h>

using namespace Rococo;
using namespace Rococo::Strings;
using namespace Rococo::Unreal;

void BuildSexyNativesCPP(IUnrealClass& classDef, StringBuilder& sb);
void BuildSexyNativesHPP(IUnrealClass& classDef, StringBuilder& sb);

void GenClassDef(IUnrealClass& classDef, crwstr rootDirectory)
{
	cstr shortName = classDef.ShortName();

	AutoFree<IDynamicStringBuilder> dsbCPP = CreateDynamicStringBuilder(64_kilobytes);

	// .cpp builder
	auto& sbCPP = dsbCPP->Builder();

	AutoFree<IDynamicStringBuilder> dsbHPP = CreateDynamicStringBuilder(16_kilobytes);

	// .HPP builder
	auto& sbHPP = dsbHPP->Builder();

	WideFilePath wTargetCPPFile;
	Format(wTargetCPPFile, L"%ls\\%hs.cpp", rootDirectory, shortName);

	WideFilePath wTargetHPPFile;
	Format(wTargetHPPFile, L"%ls\\%hs.hpp", rootDirectory, shortName);

	BuildSexyNativesCPP(classDef, sbCPP);
	BuildSexyNativesHPP(classDef, sbHPP);

	IO::SaveAsciiTextFile(IO::TargetDirectory_Root, wTargetCPPFile, *sbCPP);
	IO::SaveAsciiTextFile(IO::TargetDirectory_Root, wTargetHPPFile, *sbHPP);
}

void BuildSexyNativesCPP(IUnrealClass& classDef, StringBuilder& sb)
{
	sb << 

	R"(// Code generated by unreal-sexy.gen.core.cpp
#include <rococo.types.h>
#include <sexy.script.h>

class UObject;
class UMethod;
typedef int UnknownType;

namespace Rococo::UE5::Marshal
{
	UMethod* GetNCEUMethod(Rococo::Script::NativeCallEnvironment& e);
	UObject* GetNCEUObject(Rococo::Script::NativeCallEnvironment& e);
	void ValidateArgs(UMethod* methodRef, void* args, size_t argSize);
	void ProcessEvent(UObject* object, UMethod* methodRef, void* args);
}
)";

	if (classDef.MethodCount() > 0)
	{
		sb << R"(
namespace 
{
	using namespace Rococo;
	using namespace Rococo::Sex;
	using namespace Rococo::Script;
	using namespace Rococo::Compiler;
	using namespace Rococo::UE5::Marshal;
)";

		for (size_t i = 0; i < classDef.MethodCount(); i++)
		{
			auto& method = classDef.GetFunction(i);

			sb << "\n\tvoid ";
			method.AppendFunctionName(sb);
			sb << "(NativeCallEnvironment & _nce)\n";
			sb << "\t{\n";

			sb << "\t\tuint8* _sf = _nce.cpu.SF();\n";
			sb << "\t\tptrdiff_t _offset = 2 * sizeof(size_t);\n";

			sb << "\t\tUNUSED(_sf)\n";
			sb << "\t\tUNUSED(_offset)\n";

			sb << "\t\tUMethod* methodRef = GetNCEUMethod(_nce);\n";
			sb << "\t\tUObject* object = GetNCEUObject(_nce);\n\n";
			sb << "\t\tstruct SexyArgs_";
			method.AppendFunctionName(sb);
			sb << "\n\t\t{\n";
			
			size_t j = 0;
			for (;;)
			{
				auto* arg = method.GetArg(j++);
				if (arg == nullptr)
				{
					break;
				}

				sb << "\t\t\t";

				arg->AppendType(sb);

				if (arg->IsRef())
				{
					sb << "*";
				}

				sb << " arg_";

				arg->AppendName(sb);

				sb << ";\n";
			}

			sb << "\t\t} ";

			sb << "args;\n\n";

			sb << "\t\tValidateArgs(methodRef, &args, sizeof(args));\n";
			sb << "\t\tProcessEvent(object, methodRef, &args);\n";

			sb << "\t}\n";
		}

		sb << "}\n\n";

		sb << "namespace Rococo::Unreal\n{\n";
		sb.AppendFormat("\tvoid AddSexyNatives_Unreal_%s(UObject* worldObject)\n", classDef.ShortName());
		sb << "\t{\n\t\tUNUSED(worldObject);\n\t}\n";
		sb << "}\n";
	}
}

void BuildSexyNativesHPP(IUnrealClass& classDef, StringBuilder& sb)
{
	sb << 

R"(#pragma once
// Code generated by unreal-sexy.gen.core.cpp
#include <rococo.types.h>

namespace Rococo::Unreal
{
)";

	sb.AppendFormat("\tvoid AddSexyNatives_Unreal_%s(UObject* worldObject);\n", classDef.ShortName());
	sb << "}\n";
}