#include "unreal-sexy-gen.h"
#include <rococo.strings.h>
#include <rococo.io.h>
#include <rococo.os.h>

using namespace Rococo;
using namespace Rococo::Strings;
using namespace Rococo::Unreal;

void BuildSexyNativesCPP(IUnrealClass& classDef, StringBuilder& sb);
void BuildSexyNativesHPP(IUnrealClass& classDef, StringBuilder& sb);

void GenClassDef(IUnrealClass& classDef, crwstr rootDirectory)
{
	cstr shortName = classDef.ShortName();

	AutoFree<IDynamicStringBuilder> dsbCPP = CreateDynamicStringBuilder(64_kilobytes);

	// .cpp builder
	auto& sbCPP = dsbCPP->Builder();

	AutoFree<IDynamicStringBuilder> dsbHPP = CreateDynamicStringBuilder(16_kilobytes);

	// .HPP builder
	auto& sbHPP = dsbHPP->Builder();

	WideFilePath wTargetCPPFile;
	Format(wTargetCPPFile, L"%ls\\%hs.cpp", rootDirectory, shortName);

	WideFilePath wTargetHPPFile;
	Format(wTargetHPPFile, L"%ls\\%hs.hpp", rootDirectory, shortName);

	BuildSexyNativesCPP(classDef, sbCPP);
	BuildSexyNativesHPP(classDef, sbHPP);

	IO::SaveAsciiTextFile(IO::TargetDirectory_Root, wTargetCPPFile, *sbCPP);
	IO::SaveAsciiTextFile(IO::TargetDirectory_Root, wTargetHPPFile, *sbHPP);
}

void BuildSexyNativesCPP(IUnrealClass& classDef, StringBuilder& sb)
{
	if (classDef.MethodCount() > 0)
	{
		sb <<
R"(// Code generated by unreal-sexy.gen.core.cpp
namespace 
{
	using namespace Rococo;
	using namespace Rococo::Sex;
	using namespace Rococo::Script;
	using namespace Rococo::Compiler;
)";

		for (size_t i = 0; i < classDef.MethodCount(); i++)
		{
			auto& method = classDef.GetFunction(i);

			sb.AppendFormat("\n\tvoid %s(NativeCallEnvironment& _nce)\n", method.FunctionName());
			sb << "\t{\n";

			sb << "\t\tuint8* _sf = _nce.cpu.SF();\n";
			sb << "\t\tptrdiff_t _offset = 2 * sizeof(size_t);\n";
			sb << "\t}\n";
		}

		sb << "}\n\n";

		sb << "namespace Rococo::Unreal\n{\n";
		sb.AppendFormat("\tvoid AddSexyNatives_Unreal_%s(UObject* worldObject)\n", classDef.ShortName());
		sb << "\t{\n\t}\n";
		sb << "}\n";
	}
}

void BuildSexyNativesHPP(IUnrealClass& classDef, StringBuilder& sb)
{
	sb << 

R"(#pragma once
// Code generated by unreal-sexy.gen.core.cpp
#include <rococo.types.h>

namespace Rococo::Unreal
{
)";

	sb.AppendFormat("\tvoid AddSexyNatives_Unreal_%s(UObject* worldObject);\n", classDef.ShortName());
	sb << "}\n";
}