#pragma once
// Generated by rococo.carpenter. Timestamp: 04 July 2022 16:50:50// Excel Source: C:\work\rococo\tables\localization-text-table.xlsx

#include <tables/declarations.h>
#include <rococo.types.h>

Rococo::Strings::ILocalizedText_Sexy* FactoryConstructRococoStringsLocalizedText(Rococo::IInstallation* installation);

namespace Rococo::Strings
{

    enum class TextId: int
    {
        None, Introduction_MarcusAndronicus
    };

    bool AppendString(TextId value, IStringPopulator& populator);
    bool TryParse(const fstring& text, TextId& result);
    tuple<boolean32,TextId> TryParseTextId(const fstring& text);
    fstring ToString(TextId value);

    struct LocalizedTextRow
    {
        TextId id;
        fstring english;
        fstring german;
    };
}

#include "tables.sxh.h"

namespace Rococo::Strings
{
    ROCOCOAPI ILocalizedText_MetaData
    {
        virtual fstring GetTitle() const = 0;
        virtual fstring GetOwner() const = 0;
    };

    ROCOCOAPI ILocalizedText: protected ILocalizedText_Sexy
    {
        virtual const LocalizedTextRow& GetRow(int32 index) const = 0;
        virtual const int32 NumberOfRows() const = 0;
        virtual const LocalizedTextRow* begin() const = 0;
        virtual const LocalizedTextRow* end() const = 0;
        virtual const ILocalizedText_MetaData& Meta() const = 0;
    };

    ILocalizedText& LocalizedText();
}
