#pragma once
// Generated by rococo.carpenter. Timestamp: 29/03/2022 13:52:49
// Excel Source: C:\work\rococo\tables\localization-text-table.xlsx

#include <rococo.types.h>

namespace Rococo::Strings
{

    enum class TextId: int
    {
        None, Introduction_MarcusAndronicus
    };

    bool TryParse(const fstring& text, TextId& result);
    fstring ToString(TextId value);

    struct LocalizedText_Row
    {
        TextId id;
        fstring english;
        fstring german;
    };

    ROCOCOAPI ILocalizedText_MetaData
    {
        virtual fstring GetTitle() const = 0;
        virtual fstring GetOwner() const = 0;
    };

    ROCOCOAPI ILocalizedText
    {
        virtual const LocalizedText_Row& GetRow(int32 index) const = 0;
        virtual const int32 NumberOfRows() const = 0;
        virtual const LocalizedText_Row* begin() const = 0;
        virtual const LocalizedText_Row* end() const = 0;
        virtual const ILocalizedText_MetaData& Meta() const = 0;
    };

    ILocalizedText& LocalizedText();
}
