// Generated by rococo.carpenter. Timestamp: 15/03/2022 14:38:11
// Excel Source: C:\work\rococo\tables\periodic-table.xlsx

#include "tables\rococo.periodic-table.h"

static PeriodicTable_Row defaultRows[118] = 
{
};

namespace ANON
{
    using namespace Rococo::Science::Materials;

    struct Elements_Table_Implementation: IPeriodicTable, IPeriodicTable_MetaData
    {
        const PeriodicTable_Row& GetRow(int32 index) const override
        {
            return defaultRows[index];
        }

        const int32 NumberOfRows() const override
        {
            return 118;
        }

        const PeriodicTable_Row* begin() const override
        {
            return defaultRows;
        }

        const PeriodicTable_Row* end() const override
        {
            return defaultRows + 118;
        }

        const IPeriodicTable_MetaData& Meta() const override
        {
            return *this;
        }

        fstring GetTitle() const override
        {
            return "Periodic Table of the Elements"
        }

        fstring GetOwner() const override
        {
            return "Goodman Sciences"
        }

        fstring GetURL() const override
        {
            return "https://gist.github.com/GoodmanSciences/"
        }
    };
}

namespace Rococo::Science::Materials
{
    IPeriodicTable& GetPeriodicTable()
    {
        static ANON::Elements_Table_Implementation globalInstance;
        return globalInstance;
    }
}
