// Generated by rococo.carpenter. Timestamp: 19/03/2022 13:58:52
// Excel Source: C:\work\rococo\tables\periodic-table.xlsx

#include "tables\rococo.periodic-table.h"

static const PeriodicTable_Row defaultRows[118] = 
{
    { // #0
        1, ElementName::Hydrogen, ElementSymbol::H, 1.007, false, ElementType::Nonmetal, 2.2, 13.5984, 8.99E-05, 14.175, 20.28
    },
    { // #1
        2, ElementName::Helium, ElementSymbol::He, 4.002, false, ElementType::NobleGas, 0, 24.5874, 0.000179, 0, 4.22
    },
    { // #2
        3, ElementName::Lithium, ElementSymbol::Li, 6.941, true, ElementType::AlkaliMetal, 0.98, 5.3917, 0.534, 453.85, 1615
    },
    { // #3
        4, ElementName::Beryllium, ElementSymbol::Be, 9.012, true, ElementType::AlkalineEarthMetal, 1.57, 9.3227, 1.85, 1560.15, 2742
    },
    { // #4
        5, ElementName::Boron, ElementSymbol::B, 10.811, false, ElementType::Metalloid, 2.04, 8.298, 2.34, 2573.15, 4200
    },
    { // #5
        6, ElementName::Carbon, ElementSymbol::C, 12.011, false, ElementType::Nonmetal, 2.55, 11.2603, 2.27, 3948.15, 4300
    },
    { // #6
        7, ElementName::Nitrogen, ElementSymbol::N, 14.007, false, ElementType::Nonmetal, 3.04, 14.5341, 0.00125, 63.29, 77.36
    },
    { // #7
        8, ElementName::Oxygen, ElementSymbol::O, 15.999, false, ElementType::Nonmetal, 3.44, 13.6181, 0.00143, 50.5, 90.2
    },
    { // #8
        9, ElementName::Fluorine, ElementSymbol::F, 18.998, false, ElementType::Halogen, 3.98, 17.4228, 0.0017, 53.63, 85.03
    },
    { // #9
        10, ElementName::Neon, ElementSymbol::Ne, 20.18, false, ElementType::NobleGas, 0, 21.5645, 0.0009, 24.703, 27.07
    },
    { // #10
        11, ElementName::Sodium, ElementSymbol::Na, 22.99, true, ElementType::AlkaliMetal, 0.93, 5.1391, 0.971, 371.15, 1156
    },
    { // #11
        12, ElementName::Magnesium, ElementSymbol::Mg, 24.305, true, ElementType::AlkalineEarthMetal, 1.31, 7.6462, 1.74, 923.15, 1363
    },
    { // #12
        13, ElementName::Aluminum, ElementSymbol::Al, 26.982, true, ElementType::Metal, 1.61, 5.9858, 2.7, 933.4, 2792
    },
    { // #13
        14, ElementName::Silicon, ElementSymbol::Si, 28.086, false, ElementType::Metalloid, 1.9, 8.1517, 2.33, 1683.15, 3538
    },
    { // #14
        15, ElementName::Phosphorus, ElementSymbol::P, 30.974, false, ElementType::Nonmetal, 2.19, 10.4867, 1.82, 317.25, 553
    },
    { // #15
        16, ElementName::Sulfur, ElementSymbol::S, 32.065, false, ElementType::Nonmetal, 2.58, 10.36, 2.07, 388.51, 717.8
    },
    { // #16
        17, ElementName::Chlorine, ElementSymbol::Cl, 35.453, false, ElementType::Halogen, 3.16, 12.9676, 0.00321, 172.31, 239.11
    },
    { // #17
        18, ElementName::Argon, ElementSymbol::Ar, 39.948, false, ElementType::NobleGas, 0, 15.7596, 0.00178, 83.96, 87.3
    },
    { // #18
        19, ElementName::Potassium, ElementSymbol::K, 39.098, true, ElementType::AlkaliMetal, 0.82, 4.3407, 0.862, 336.5, 1032
    },
    { // #19
        20, ElementName::Calcium, ElementSymbol::Ca, 40.078, true, ElementType::AlkalineEarthMetal, 1, 6.1132, 1.54, 1112.15, 1757
    },
    { // #20
        21, ElementName::Scandium, ElementSymbol::Sc, 44.956, true, ElementType::TransitionMetal, 1.36, 6.5615, 2.99, 1812.15, 3109
    },
    { // #21
        22, ElementName::Titanium, ElementSymbol::Ti, 47.867, true, ElementType::TransitionMetal, 1.54, 6.8281, 4.54, 1933.15, 3560
    },
    { // #22
        23, ElementName::Vanadium, ElementSymbol::V, 50.942, true, ElementType::TransitionMetal, 1.63, 6.7462, 6.11, 2175.15, 3680
    },
    { // #23
        24, ElementName::Chromium, ElementSymbol::Cr, 51.996, true, ElementType::TransitionMetal, 1.66, 6.7665, 7.15, 2130.15, 2944
    },
    { // #24
        25, ElementName::Manganese, ElementSymbol::Mn, 54.938, true, ElementType::TransitionMetal, 1.55, 7.434, 7.44, 1519.15, 2334
    },
    { // #25
        26, ElementName::Iron, ElementSymbol::Fe, 55.845, true, ElementType::TransitionMetal, 1.83, 7.9024, 7.87, 1808.15, 3134
    },
    { // #26
        27, ElementName::Cobalt, ElementSymbol::Co, 58.933, true, ElementType::TransitionMetal, 1.88, 7.881, 8.86, 1768.15, 3200
    },
    { // #27
        28, ElementName::Nickel, ElementSymbol::Ni, 58.693, true, ElementType::TransitionMetal, 1.91, 7.6398, 8.91, 1726.15, 3186
    },
    { // #28
        29, ElementName::Copper, ElementSymbol::Cu, 63.546, true, ElementType::TransitionMetal, 1.9, 7.7264, 8.96, 1357.75, 2835
    },
    { // #29
        30, ElementName::Zinc, ElementSymbol::Zn, 65.38, true, ElementType::TransitionMetal, 1.65, 9.3942, 7.13, 692.88, 1180
    },
    { // #30
        31, ElementName::Gallium, ElementSymbol::Ga, 69.723, true, ElementType::Metal, 1.81, 5.9993, 5.91, 302.91, 2477
    },
    { // #31
        32, ElementName::Germanium, ElementSymbol::Ge, 72.64, false, ElementType::Metalloid, 2.01, 7.8994, 5.32, 1211.45, 3106
    },
    { // #32
        33, ElementName::Arsenic, ElementSymbol::As, 74.922, false, ElementType::Metalloid, 2.18, 9.7886, 5.78, 1090.15, 887
    },
    { // #33
        34, ElementName::Selenium, ElementSymbol::Se, 78.96, false, ElementType::Nonmetal, 2.55, 9.7524, 4.81, 494.15, 958
    },
    { // #34
        35, ElementName::Bromine, ElementSymbol::Br, 79.904, false, ElementType::Halogen, 2.96, 11.8138, 3.12, 266.05, 332
    },
    { // #35
        36, ElementName::Krypton, ElementSymbol::Kr, 83.798, false, ElementType::NobleGas, 0, 13.9996, 0.00373, 115.93, 119.93
    },
    { // #36
        37, ElementName::Rubidium, ElementSymbol::Rb, 85.468, true, ElementType::AlkaliMetal, 0.82, 4.1771, 1.53, 312.79, 961
    },
    { // #37
        38, ElementName::Strontium, ElementSymbol::Sr, 87.62, true, ElementType::AlkalineEarthMetal, 0.95, 5.6949, 2.64, 1042.15, 1655
    },
    { // #38
        39, ElementName::Yttrium, ElementSymbol::Y, 88.906, true, ElementType::TransitionMetal, 1.22, 6.2173, 4.47, 1799.15, 3609
    },
    { // #39
        40, ElementName::Zirconium, ElementSymbol::Zr, 91.224, true, ElementType::TransitionMetal, 1.33, 6.6339, 6.51, 2125.15, 4682
    },
    { // #40
        41, ElementName::Niobium, ElementSymbol::Nb, 92.906, true, ElementType::TransitionMetal, 1.6, 6.7589, 8.57, 2741.15, 5017
    },
    { // #41
        42, ElementName::Molybdenum, ElementSymbol::Mo, 95.96, true, ElementType::TransitionMetal, 2.16, 7.0924, 10.2, 2890.15, 4912
    },
    { // #42
        43, ElementName::Technetium, ElementSymbol::Tc, 98, true, ElementType::TransitionMetal, 1.9, 7.28, 11.5, 2473.15, 5150
    },
    { // #43
        44, ElementName::Ruthenium, ElementSymbol::Ru, 101.07, true, ElementType::TransitionMetal, 2.2, 7.3605, 12.4, 2523.15, 4423
    },
    { // #44
        45, ElementName::Rhodium, ElementSymbol::Rh, 102.906, true, ElementType::TransitionMetal, 2.28, 7.4589, 12.4, 2239.15, 3968
    },
    { // #45
        46, ElementName::Palladium, ElementSymbol::Pd, 106.42, true, ElementType::TransitionMetal, 2.2, 8.3369, 12, 1825.15, 3236
    },
    { // #46
        47, ElementName::Silver, ElementSymbol::Ag, 107.868, true, ElementType::TransitionMetal, 1.93, 7.5762, 10.5, 1234.15, 2435
    },
    { // #47
        48, ElementName::Cadmium, ElementSymbol::Cd, 112.411, true, ElementType::TransitionMetal, 1.69, 8.9938, 8.69, 594.33, 1040
    },
    { // #48
        49, ElementName::Indium, ElementSymbol::In, 114.818, true, ElementType::Metal, 1.78, 5.7864, 7.31, 429.91, 2345
    },
    { // #49
        50, ElementName::Tin, ElementSymbol::Sn, 118.71, true, ElementType::Metal, 1.96, 7.3439, 7.29, 505.21, 2875
    },
    { // #50
        51, ElementName::Antimony, ElementSymbol::Sb, 121.76, false, ElementType::Metalloid, 2.05, 8.6084, 6.69, 904.05, 1860
    },
    { // #51
        52, ElementName::Tellurium, ElementSymbol::Te, 127.6, false, ElementType::Metalloid, 2.1, 9.0096, 6.23, 722.8, 1261
    },
    { // #52
        53, ElementName::Iodine, ElementSymbol::I, 126.904, false, ElementType::Halogen, 2.66, 10.4513, 4.93, 386.65, 457.4
    },
    { // #53
        54, ElementName::Xenon, ElementSymbol::Xe, 131.293, false, ElementType::NobleGas, 0, 12.1298, 0.00589, 161.45, 165.03
    },
    { // #54
        55, ElementName::Cesium, ElementSymbol::Cs, 132.905, true, ElementType::AlkaliMetal, 0.79, 3.8939, 1.87, 301.7, 944
    },
    { // #55
        56, ElementName::Barium, ElementSymbol::Ba, 137.327, true, ElementType::AlkalineEarthMetal, 0.89, 5.2117, 3.59, 1002.15, 2170
    },
    { // #56
        57, ElementName::Lanthanum, ElementSymbol::La, 138.905, true, ElementType::Lanthanide, 1.1, 5.5769, 6.15, 1193.15, 3737
    },
    { // #57
        58, ElementName::Cerium, ElementSymbol::Ce, 140.116, true, ElementType::Lanthanide, 1.12, 5.5387, 6.77, 1071.15, 3716
    },
    { // #58
        59, ElementName::Praseodymium, ElementSymbol::Pr, 140.908, true, ElementType::Lanthanide, 1.13, 5.473, 6.77, 1204.15, 3793
    },
    { // #59
        60, ElementName::Neodymium, ElementSymbol::Nd, 144.242, true, ElementType::Lanthanide, 1.14, 5.525, 7.01, 1289.15, 3347
    },
    { // #60
        61, ElementName::Promethium, ElementSymbol::Pm, 145, true, ElementType::Lanthanide, 1.13, 5.582, 7.26, 1204.15, 3273
    },
    { // #61
        62, ElementName::Samarium, ElementSymbol::Sm, 150.36, true, ElementType::Lanthanide, 1.17, 5.6437, 7.52, 1345.15, 2067
    },
    { // #62
        63, ElementName::Europium, ElementSymbol::Eu, 151.964, true, ElementType::Lanthanide, 1.2, 5.6704, 5.24, 1095.15, 1802
    },
    { // #63
        64, ElementName::Gadolinium, ElementSymbol::Gd, 157.25, true, ElementType::Lanthanide, 1.2, 6.1501, 7.9, 1585.15, 3546
    },
    { // #64
        65, ElementName::Terbium, ElementSymbol::Tb, 158.925, true, ElementType::Lanthanide, 1.2, 5.8638, 8.23, 1630.15, 3503
    },
    { // #65
        66, ElementName::Dysprosium, ElementSymbol::Dy, 162.5, true, ElementType::Lanthanide, 1.22, 5.9389, 8.55, 1680.15, 2840
    },
    { // #66
        67, ElementName::Holmium, ElementSymbol::Ho, 164.93, true, ElementType::Lanthanide, 1.23, 6.0215, 8.8, 1743.15, 2993
    },
    { // #67
        68, ElementName::Erbium, ElementSymbol::Er, 167.259, true, ElementType::Lanthanide, 1.24, 6.1077, 9.07, 1795.15, 3503
    },
    { // #68
        69, ElementName::Thulium, ElementSymbol::Tm, 168.934, true, ElementType::Lanthanide, 1.25, 6.1843, 9.32, 1818.15, 2223
    },
    { // #69
        70, ElementName::Ytterbium, ElementSymbol::Yb, 173.054, true, ElementType::Lanthanide, 1.1, 6.2542, 6.97, 1097.15, 1469
    },
    { // #70
        71, ElementName::Lutetium, ElementSymbol::Lu, 174.967, true, ElementType::Lanthanide, 1.27, 5.4259, 9.84, 1936.15, 3675
    },
    { // #71
        72, ElementName::Hafnium, ElementSymbol::Hf, 178.49, true, ElementType::TransitionMetal, 1.3, 6.8251, 13.3, 2500.15, 4876
    },
    { // #72
        73, ElementName::Tantalum, ElementSymbol::Ta, 180.948, true, ElementType::TransitionMetal, 1.5, 7.5496, 16.7, 3269.15, 5731
    },
    { // #73
        74, ElementName::Wolfram, ElementSymbol::W, 183.84, true, ElementType::TransitionMetal, 2.36, 7.864, 19.3, 3680.15, 5828
    },
    { // #74
        75, ElementName::Rhenium, ElementSymbol::Re, 186.207, true, ElementType::TransitionMetal, 1.9, 7.8335, 21, 3453.15, 5869
    },
    { // #75
        76, ElementName::Osmium, ElementSymbol::Os, 190.23, true, ElementType::TransitionMetal, 2.2, 8.4382, 22.6, 3300.15, 5285
    },
    { // #76
        77, ElementName::Iridium, ElementSymbol::Ir, 192.217, true, ElementType::TransitionMetal, 2.2, 8.967, 22.6, 2716.15, 4701
    },
    { // #77
        78, ElementName::Platinum, ElementSymbol::Pt, 195.084, true, ElementType::TransitionMetal, 2.28, 8.9587, 21.5, 2045.15, 4098
    },
    { // #78
        79, ElementName::Gold, ElementSymbol::Au, 196.967, true, ElementType::TransitionMetal, 2.54, 9.2255, 19.3, 1337.73, 3129
    },
    { // #79
        80, ElementName::Mercury, ElementSymbol::Hg, 200.59, true, ElementType::TransitionMetal, 2, 10.4375, 13.5, 234.43, 630
    },
    { // #80
        81, ElementName::Thallium, ElementSymbol::Tl, 204.383, true, ElementType::Metal, 2.04, 6.1082, 11.9, 577.15, 1746
    },
    { // #81
        82, ElementName::Lead, ElementSymbol::Pb, 207.2, true, ElementType::Metal, 2.33, 7.4167, 11.3, 600.75, 2022
    },
    { // #82
        83, ElementName::Bismuth, ElementSymbol::Bi, 208.98, true, ElementType::Metal, 2.02, 7.2856, 9.81, 544.67, 1837
    },
    { // #83
        84, ElementName::Polonium, ElementSymbol::Po, 210, false, ElementType::Metalloid, 2, 8.417, 9.32, 527.15, 1235
    },
    { // #84
        85, ElementName::Astatine, ElementSymbol::At, 210, false, ElementType::NobleGas, 2.2, 9.3, 7, 575.15, 610
    },
    { // #85
        86, ElementName::Radon, ElementSymbol::Rn, 222, true, ElementType::AlkaliMetal, 0, 10.7485, 0.00973, 202.15, 211.3
    },
    { // #86
        87, ElementName::Francium, ElementSymbol::Fr, 223, true, ElementType::AlkalineEarthMetal, 0.7, 4.0727, 1.87, 300.15, 950
    },
    { // #87
        88, ElementName::Radium, ElementSymbol::Ra, 226, true, ElementType::Actinide, 0.9, 5.2784, 5.5, 973.15, 2010
    },
    { // #88
        89, ElementName::Actinium, ElementSymbol::Ac, 227, true, ElementType::Actinide, 1.1, 5.17, 10.1, 1323.15, 3471
    },
    { // #89
        90, ElementName::Thorium, ElementSymbol::Th, 232.038, true, ElementType::Actinide, 1.3, 6.3067, 11.7, 2028.15, 5061
    },
    { // #90
        91, ElementName::Protactinium, ElementSymbol::Pa, 231.036, true, ElementType::Actinide, 1.5, 5.89, 15.4, 1873.15, 4300
    },
    { // #91
        92, ElementName::Uranium, ElementSymbol::U, 238.029, true, ElementType::Actinide, 1.38, 6.1941, 19, 1405.15, 4404
    },
    { // #92
        93, ElementName::Neptunium, ElementSymbol::Np, 237, true, ElementType::Actinide, 1.36, 6.2657, 20.5, 913.15, 4273
    },
    { // #93
        94, ElementName::Plutonium, ElementSymbol::Pu, 244, true, ElementType::Actinide, 1.28, 6.0262, 19.8, 913.15, 3501
    },
    { // #94
        95, ElementName::Americium, ElementSymbol::Am, 243, true, ElementType::Actinide, 1.3, 5.9738, 13.7, 1267.15, 2880
    },
    { // #95
        96, ElementName::Curium, ElementSymbol::Cm, 247, true, ElementType::Actinide, 1.3, 5.9915, 13.5, 1340.15, 3383
    },
    { // #96
        97, ElementName::Berkelium, ElementSymbol::Bk, 247, true, ElementType::Actinide, 1.3, 6.1979, 14.8, 1259.15, 983
    },
    { // #97
        98, ElementName::Californium, ElementSymbol::Cf, 251, true, ElementType::Actinide, 1.3, 6.2817, 15.1, 1925.15, 1173
    },
    { // #98
        99, ElementName::Einsteinium, ElementSymbol::Es, 252, true, ElementType::Actinide, 1.3, 6.42, 13.5, 1133.15, 0
    },
    { // #99
        100, ElementName::Fermium, ElementSymbol::Fm, 257, true, ElementType::Actinide, 1.3, 6.5, 0, 0, 0
    },
    { // #100
        101, ElementName::Mendelevium, ElementSymbol::Md, 258, true, ElementType::Actinide, 1.3, 6.58, 0, 0, 0
    },
    { // #101
        102, ElementName::Nobelium, ElementSymbol::No, 259, true, ElementType::Actinide, 1.3, 6.65, 0, 0, 0
    },
    { // #102
        103, ElementName::Lawrencium, ElementSymbol::Lr, 262, true, ElementType::Actinide, 0, 0, 0, 0, 0
    },
    { // #103
        104, ElementName::Rutherfordium, ElementSymbol::Rf, 261, true, ElementType::Transactinide, 0, 0, 18.1, 0, 0
    },
    { // #104
        105, ElementName::Dubnium, ElementSymbol::Db, 262, true, ElementType::Transactinide, 0, 0, 39, 0, 0
    },
    { // #105
        106, ElementName::Seaborgium, ElementSymbol::Sg, 266, true, ElementType::Transactinide, 0, 0, 35, 0, 0
    },
    { // #106
        107, ElementName::Bohrium, ElementSymbol::Bh, 264, true, ElementType::Transactinide, 0, 0, 37, 0, 0
    },
    { // #107
        108, ElementName::Hassium, ElementSymbol::Hs, 267, true, ElementType::Transactinide, 0, 0, 41, 0, 0
    },
    { // #108
        109, ElementName::Meitnerium, ElementSymbol::Mt, 268, true, ElementType::Transactinide, 0, 0, 35, 0, 0
    },
    { // #109
        110, ElementName::Darmstadtium, ElementSymbol::Ds, 271, true, ElementType::Transactinide, 0, 0, 0, 0, 0
    },
    { // #110
        111, ElementName::Roentgenium, ElementSymbol::Rg, 272, true, ElementType::Transactinide, 0, 0, 0, 0, 0
    },
    { // #111
        112, ElementName::Copernicium, ElementSymbol::Cn, 285, true, ElementType::Transactinide, 0, 0, 0, 0, 0
    },
    { // #112
        113, ElementName::Nihonium, ElementSymbol::Nh, 284, true, ElementType::, 0, 0, 0, 0, 0
    },
    { // #113
        114, ElementName::Flerovium, ElementSymbol::Fl, 289, true, ElementType::Transactinide, 0, 0, 0, 0, 0
    },
    { // #114
        115, ElementName::Moscovium, ElementSymbol::Mc, 288, true, ElementType::, 0, 0, 0, 0, 0
    },
    { // #115
        116, ElementName::Livermorium, ElementSymbol::Lv, 292, true, ElementType::Transactinide, 0, 0, 0, 0, 0
    },
    { // #116
        117, ElementName::Tennessine, ElementSymbol::Ts, 295, false, ElementType::, 0, 0, 0, 0, 0
    },
    { // #117
        118, ElementName::Oganesson, ElementSymbol::Og, 294, false, ElementType::NobleGas, 0, 0, 0, 0, 0
    }
};

namespace ANON
{
    using namespace Rococo::Science::Materials;

    struct Elements_Table_Implementation: IPeriodicTable, IPeriodicTable_MetaData
    {
        const PeriodicTable_Row& GetRow(int32 index) const override
        {
            return defaultRows[index];
        }

        const int32 NumberOfRows() const override
        {
            return 118;
        }

        const PeriodicTable_Row* begin() const override
        {
            return defaultRows;
        }

        const PeriodicTable_Row* end() const override
        {
            return defaultRows + 118;
        }

        const IPeriodicTable_MetaData& Meta() const override
        {
            return *this;
        }

        fstring GetTitle() const override
        {
            return "Periodic Table of the Elements"
        }

        fstring GetOwner() const override
        {
            return "Goodman Sciences"
        }

        fstring GetURL() const override
        {
            return "https://gist.github.com/GoodmanSciences/"
        }
    };
}

namespace Rococo::Science::Materials
{
    IPeriodicTable& GetPeriodicTable()
    {
        static ANON::Elements_Table_Implementation globalInstance;
        return globalInstance;
    }
}
