#pragma once
// Generated by rococo.carpenter. Timestamp: 03/04/2022 13:55:00
// Excel Source: C:\work\rococo\tables\quotes-table.xlsx

#include <rococo.types.h>

namespace Rococo::Quotes
{

    enum class QuoteId: int
    {
        None, DoctorJohnson1, Whistle, Biden
    };

    bool TryParse(const fstring& text, QuoteId& result);
    fstring ToString(QuoteId value);

    struct Quotes_Row
    {
        QuoteId id;
        fstring text;
    };

    ROCOCOAPI IQuotes_MetaData
    {
        virtual fstring GetTitle() const = 0;
        virtual fstring GetOwner() const = 0;
    };

    ROCOCOAPI IQuotes
    {
        virtual const Quotes_Row& GetRow(int32 index) const = 0;
        virtual const int32 NumberOfRows() const = 0;
        virtual const IQuotes_MetaData& Meta() const = 0;
    };


    ROCOCOAPI IQuotesSupervisor: IQuotes
    {
        virtual void Free() = 0;
    };

    IQuotesSupervisor* GetQuoteTable();
}
