#pragma once
// Generated by rococo.carpenter. Timestamp: 10/04/2022 22:34:39
// Excel Source: C:\work\rococo\tables\users.demo.xlsx

#include <rococo.types.h>

namespace Rococo::Test::UserDemo
{
    ROCOCOAPI IUsers_Row
    {
        virtual fstring GetOwnerId() const = 0;
        virtual int64 GetPurchaseId() const = 0;
    };

    ROCOCOAPI IUsers_MetaData
    {
        virtual fstring GetTitle() const = 0;
        virtual fstring GetOwner() const = 0;
    };

    ROCOCOAPI IUsers
    {
        virtual const IUsers_Row& GetRow(int32 index) const = 0;
        virtual const int32 NumberOfRows() const = 0;
        virtual const IUsers_MetaData& Meta() const = 0;
        virtual const IUsers_Row* FindRowByOwnerId(fstring ownerId, int32& index) const = 0;
        virtual const IUsers_Row* FindRowByPurchaseId(int64 purchaseId, int32& index) const = 0;
    };

    ROCOCOAPI IUsersSupervisor: IUsers
    {
        virtual void Free() = 0;
    };

    IUsersSupervisor* GetUserTable(IInstallation& installation);
}
