// Copyright (c) 2025 Mark Anthony Taylor. All rights reserved. Email: mark.anthony.taylor@gmail.com.
// Bundle generated by Build.Rococo.GUI.cs
// Created: Oct 2025 UTC
#pragma once

#pragma once

typedef struct DataStream
{
	const unsigned char* sourceData;
	size_t dataLengthBytes;
	const unsigned char* end;
	const unsigned char* readPosition;
} DataStream;
