// Bundle generated by Build.Rococo.GUI.cs
// Created: Oct 2025 UTC

#include "rococo.os.UE5.h"
// Copyright (c)2025 Mark Anthony Taylor (mark.anthony.taylor@gmail.com). All rights reserved.
// This software is open source, but not free. Check the rococo master branch for the latest Copyright rules that applies to this software

#include <HAL/Platform.h>

#ifdef _WIN32
# pragma warning(disable: 4458) // this is my coding style and I don't see many errors arising out of the choice of style
# pragma warning(disable: 4265) // virtualized destructors are irrelevant for these classes using the Free() pattern
#else
# pragma clang diagnostic push
# pragma clang diagnostic ignored "-Wshadow"
# pragma clang diagnostic ignored "-Wdelete-non-abstract-non-virtual-dtor"
# pragma clang diagnostic ignored "-Woverloaded-virtual"
# pragma clang diagnostic ignored "-Wmissing-braces"
#endif
#include <D:/work/rococo/source/rococo/rococo.util/rococo.strings.cpp>
#include <D:/work/rococo/source/rococo/rococo.util/rococo.base.cpp>
#include <D:/work/rococo/source/rococo/rococo.util/rococo.heap.string.cpp>
#include <D:/work/rococo/source/rococo/rococo.util/rococo.allocators.cpp>
#include <D:/work/rococo/source/rococo/rococo.util/rococo.throw.cr_sex.cpp>
#ifdef _WIN32
# pragma warning(default: 4458)
# pragma warning(default: 4265)
#else
# pragma clang diagnostic pop
#endif

