// Generated by Build.Rococo.GUI.cs. Copied from D:\work\rococo\UE5\RococoTestFPS\Plugins\RococoGui\Source\RococoGui\Public\ReflectedGameOptionsBuilder.h on Oct 2025 UTC

#pragma once

#include <CoreMinimal.h>

namespace Rococo::GreatSex
{
	struct IGreatSexGenerator;

	struct IReflectedGameOptionsBuilder
	{
		virtual void AddMethods(UObject& object) = 0;
		virtual void Free() = 0;
		virtual void ReflectIntoGenerator(UObject& object, const FString& optionCategory, IGreatSexGenerator& generator) = 0;
	};

	ROCOCO_GUI_API IReflectedGameOptionsBuilder* CreateReflectedGameOptionsBuilder();
}
