#pragma once

// Generated at: Feb 23 2022 11:16 UTC
// Based on the template file: C:\work\rococo\rococo.cpp_master\component.template.h
#include <rococo.types.h>
#include <rococo.component.entities.h>
#include "components.h"

namespace Rococo::Components::Sys
{
    struct ComponentFactories
    {
        IFireComponentFactory& fireComponentFactory;
        IWaterComponentFactory& waterComponentFactory;
    };

    struct ActiveComponents
    {
        bool hasFireComponent : 1;
        bool hasWaterComponent : 1;
    };

    ROCOCOAPI IROIDCallback
    {
        enum EControlLogic { CONTINUE, BREAK };
        virtual EControlLogic OnROID(ROID id) = 0;
    };

    template<class T> ROCOCOAPI IComponentCallback
    {
        enum EControlLogic { CONTINUE, BREAK };
        virtual EControlLogic OnComponent(ROID id, T& item) = 0;
    };

    ROCOCOAPI IRCObjectTableBase
    {
        // Returns the number of ROIDS in use. 
        [[nodiscard]] virtual size_t ActiveRoidCount() const = 0;

        // Called periodically to remove deprecated and unreferenced entities and components
        virtual void CollectGarbage() = 0;

        // Mark a ROID as deprecated, existant Ref<IComponentInterfaces> will be valid, but, when all new references can no longer be accessed.
        virtual bool Deprecate(ROID roid) = 0;

        // Mark all ROIDs as deprecated. Best followed up by a CollectGarbage.
        virtual void DeprecateAll() = 0;

        // Invoke the cb.OnROID for every ROID
        virtual void Enumerate(IROIDCallback& cb) = 0;

        // Returns the component flags structure.
        [[nodiscard]] virtual ActiveComponents GetActiveComponents(ROID id) const = 0;

        // Returns true if a ROID is in the system and not deprecated
        [[nodiscard]] virtual bool IsActive(ROID id) const = 0;

        // Returns the maximum number of ROIDS that can be managed by this system.
        [[nodiscard]] virtual uint32 MaxTableEntries() const = 0;

        // Creates a new ROID and returns the result
        [[nodiscard]] virtual ROID NewROID() = 0;
    };

    ROCOCOAPI IRCObjectTable: IRCObjectTableBase
    {     

        [[nodiscard]] virtual Ref<IFireComponent> AddFireComponent(ROID id) = 0;

        // Marks the FireComponent as deprecated, when all outstanding refences are out of scope the object can be garbage collected
        virtual bool DeprecateFireComponent(ROID id) = 0;

        // Enumerate all FireComponent elements. The reference in the callback cb.OnComponent is valid only for the callback lifetime. 
        // While enumerating garbage collection is suspended and new items cannot be added.
        [[nodiscard]] virtual void EnumerateFireComponents(IComponentCallback<IFireComponent>& cb) = 0;

        // Attemp to get a reference to the component with a given ROID
        virtual Ref<IFireComponent> GetFireComponent(ROID id) = 0;

        // Populate an array of ROIDs and return the number appended. If roidOutput is null then the return value is the number of FireComponents in the table
        [[nodiscard]] virtual size_t GetFireComponentIDs(ROID* roidOutput, size_t nElementsInOutput) = 0;

        [[nodiscard]] virtual Ref<IWaterComponent> AddWaterComponent(ROID id) = 0;

        // Marks the WaterComponent as deprecated, when all outstanding refences are out of scope the object can be garbage collected
        virtual bool DeprecateWaterComponent(ROID id) = 0;

        // Enumerate all WaterComponent elements. The reference in the callback cb.OnComponent is valid only for the callback lifetime. 
        // While enumerating garbage collection is suspended and new items cannot be added.
        [[nodiscard]] virtual void EnumerateWaterComponents(IComponentCallback<IWaterComponent>& cb) = 0;

        // Attemp to get a reference to the component with a given ROID
        virtual Ref<IWaterComponent> GetWaterComponent(ROID id) = 0;

        // Populate an array of ROIDs and return the number appended. If roidOutput is null then the return value is the number of WaterComponents in the table
        [[nodiscard]] virtual size_t GetWaterComponentIDs(ROID* roidOutput, size_t nElementsInOutput) = 0;
    };

    ROCOCOAPI IRCObjectTableSupervisor : IRCObjectTable
    {
        virtual void Free() = 0;
    };

    namespace Factories
    {
        /*
        *   Returns an interface to a new RCO ECS system.
        *   The factories structure is generated by rococo.cpp_master acting upon component.template.cpp and component.template.h
        *   The maxSizeInBytes value gives the memory dedicated to the entity tables, not the associated components. 2GB is the default
        */
        [[nodiscard]] IRCObjectTableSupervisor* Create_RCO_EntityComponentSystem(ComponentFactories& factories, uint64 maxSizeInBytes = 2 * 1024 * 1024 * 1024ULL);
    }
} // Rococo::Components::Sys

