cd /D "%~dp0"
del "C:\Program Files\Notepad++\plugins\sexystudio.4.notepad++\*.dll"  
del "C:\Program Files\Notepad++\plugins\sexystudio.4.notepad++.debug\*.dll"  
copy "..\bin\sexystudio.4.notepad++.dll"       "C:\Program Files\Notepad++\plugins\sexystudio.4.notepad++"  
copy "..\bin\sexystudio.dll"                   "C:\Program Files\Notepad++\plugins\sexystudio.4.notepad++" 
copy "..\bin\sexystudio.4.notepad++.debug.dll" "C:\Program Files\Notepad++\plugins\sexystudio.4.notepad++.debug"  
copy "..\bin\sexystudio.debug.dll"             "C:\Program Files\Notepad++\plugins\sexystudio.4.notepad++.debug" 