#pragma once

// Generated by BennyHill on 4/5/2025 17:49:39 UTC

namespace Rococo { 
	struct TriangleScan
	{
		ID_ENTITY id;
		ID_SYS_MESH idMesh;
		Triangle t;
	};
}
namespace Rococo { 
	struct HQFontDef
	{
		int32 fontSize;
		boolean32 isItalic;
		boolean32 isBold;
	};
}
