#pragma once

// Generated by BennyHill on 10/10/2025 10:22:23 UTC

namespace Rococo { 
	struct TriangleScan
	{
		ID_ENTITY id;
		ID_SYS_MESH idMesh;
		Triangle t;
	};
}
namespace Rococo { 
	struct HQFontDef
	{
		int32 fontSize;
		boolean32 isItalic;
		boolean32 isBold;
	};
}
