// Bundle generated by Rococo.Util.Build.cs
// Created: 15 Jun 2025 10:20:20 UTC

#include "rococo.zlib.UE5.h"
// Copyright (c)2025 Mark Anthony Taylor (mark.anthony.taylor@gmail.com). All rights reserved.
// This software is open source, but not free. Check the rococo master branch for the latest Copyright rules that applies to this software

#ifdef _WIN32
# pragma warning(disable: 4456)
#else
#endif
#include "D:/work/rococo/source/3rd-Party/zlib/trees.c"
#ifdef _WIN32
# pragma warning(default: 4456)
#else
#endif
