SET "SEXYPATH=\work\bloke\sexy\"
SET "BENNYEXE=Bin\Win32Release\sexy.bennyhill.exe"
SET "PROJECTROOT=sexy.bennyhill\api.generator\"
SET "PROJECTFILE=api.sxh"
SET "MATHS_SRC=cpp\*.maths.*"
SET "MATHS_TRG=SS\sexy.nativelib.maths\"
CALL %SEXYPATH%%BENNYEXE% %SEXYPATH%%PROJECTROOT% %SEXYPATH%%PROJECTROOT%%PROJECTFILE% null
COPY %SEXYPATH%%PROJECTROOT%%MATHS_SRC% %SEXYPATH%%MATHS_TRG%
DEL %SEXYPATH%%PROJECTROOT%%MATHS_SRC%
