// Bundle generated by Rococo.Util.Build.cs
// Created: 14 Jun 2025 13:45:26 UTC

#include "rococo.tiff.UE5.h"
// Copyright (c)2025 Mark Anthony Taylor (mark.anthony.taylor@gmail.com). All rights reserved.
// This software is open source, but not free. Check the rococo master branch for the latest Copyright rules that applies to this software

#ifdef _WIN32
# pragma warning(disable: 4456)
# pragma warning(disable: 4459)
#else
#endif
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/lfind.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_aux.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_close.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_codec.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_color.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_compress.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_dir.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_dirinfo.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_dirread.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_dirwrite.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_dumpmode.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_error.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_extension.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_fax3.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_fax3sm.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_flush.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_getimage.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_jbig.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_jpeg.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_jpeg_12.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_luv.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_lzma.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_lzw.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_next.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_ojpeg.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_open.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_packbits.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_pixarlog.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_predict.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_print.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_read.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_strip.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_swab.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_thunder.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_tile.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_version.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_warning.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_write.c>
#include <D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_zip.c>
#ifdef _WIN32
# pragma warning(default: 4456)
# pragma warning(disable: 4459)
#else
#endif
