// Bundle generated by Rococo.TiffLib.Build.cs
// Created: 16 Jun 2025 09:38:53 UTC

#include "rococo.tiff.UE5.h"
#include "rococo.tiff.prelude.h"

#ifndef _WIN32
#include <stdarg.h>
enum { _TRUNCATE = -1 };
int _vsnprintf_s(char* message, size_t capacity, size_t nBytesToWrite, const char* format, va_list args);
#endif
#include "D:/work/rococo/source/3rd-Party/libtiff/bloke.tiff.cpp"
#ifdef _WIN32
# pragma warning(default: 4456)
# pragma warning(default: 4459)
# pragma warning(default: 4996)
# undef _CRT_SECURE_NO_WARNINGS 
#else
#endif
