// Bundle generated by Rococo.Util.Build.cs
// Created: 14 Jun 2025 16:22:22 UTC

#include "rococo.tiff.UE5.h"
#ifdef _WIN32
# define _CRT_SECURE_NO_WARNINGS 
# pragma warning(disable: 4456)
# pragma warning(disable: 4459)
#else
#endif
#include "D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_dumpmode.c"
#ifdef _WIN32
# pragma warning(default: 4456)
# pragma warning(disable: 4459)
# undef _CRT_SECURE_NO_WARNINGS 
#else
#endif
