// Bundle generated by Rococo.TiffLib.Build.cs
// Created: 15 Jun 2025 14:25:34 UTC

#include "rococo.tiff.UE5.h"
#ifdef _WIN32
# pragma warning(disable: 4456)
# pragma warning(disable: 4459)
# pragma warning(disable: 4996)
#else
#endif
#include "D:/work/rococo/source/3rd-Party/libtiff/libtiff/tif_warning.c"
#ifdef _WIN32
# pragma warning(default: 4456)
# pragma warning(default: 4459)
# pragma warning(default: 4996)
# undef _CRT_SECURE_NO_WARNINGS 
#else
#endif
